### ISSUE TITLE
Issue with running table detection and structure recognition

### ISSUE THREAD

**Issue by Kehindeajayi01** [Psarpei/Multi-Type-TD-TSR#8]
Hi,
Thanks for the great work. I am trying to run your tdtsr.py script on my custom images but I am running into error with the config file:

<img width="566" alt="Screen Shot 1400-10-24 at 11 36 49" src="https://user-images.githubusercontent.com/43017928/149551516-8831fa5a-55b3-4af8-bc3a-f54828abed9d.png">
'
Any idea how to resolve this will be appreciated. Thanks

**Comment by Kehindeajayi01** [comment]
I have managed to resolve the issue above. However, after running the tdtsr.py script, there were bunch of warnings and no output was generated according to README file. Do I need to do any preprocessing on my table images before running the tdtsr.py module?


<img width="617" alt="Screen Shot 1400-10-24 at 13 35 34" src="https://user-images.githubusercontent.com/43017928/149567461-d7a79a10-905a-4a74-a80f-41d09a879940.png">

**Comment by salman-moh** [comment]
@Kehindeajayi01 
how did you solve this error? trying to get a command line for tdtsr on colab.
 What application are you working on? I'm applying these to medical documents to extract table with contents to obtain a dataframe in pandas at the end.

**Comment by Kehindeajayi01** [comment]
> @Kehindeajayi01 how did you solve this error? trying to get a command line for tdtsr on colab. What application are you working on? I'm applying these to medical documents to extract table with contents to obtain a dataframe in pandas at the end.

@salman-moh : I ran the code on google colab. This method mainly generates xml files for the table structures and not the text content.

**Comment by temiwale88** [comment]
Thanks @Kehindeajayi01 . What did you do with the xml files? Also, how are you resolving the text extraction process? (I'm sure there are better algorithms now). Thanks!

**Comment by Dipankar1997161** [comment]
> Thanks @Kehindeajayi01 . What did you do with the xml files? Also, how are you resolving the text extraction process? (I'm sure there are better algorithms now). Thanks!

on their collab, there is tesseract ocr which they used for extraction and then popped it to csv. but I can't find the function here.

Did you ?
